stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - echo "Building the project..."
    - mkdir dist
    - echo "Build output" > dist/output.txt
  artifacts:
    paths:
      - dist/

test_job:
  stage: test
  script:
    - echo "Running tests..."
    - cat dist/output.txt
  dependencies:
    - build_job

deploy_job:
  stage: deploy
  script:
    - echo "Deploying the project..."
    - cat dist/output.txt
  dependencies:
    - build_job
